[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#C6283D"
base = "light"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E8EFF7"
textColor = "#20354B"
font = "sans serif"
