[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1266A1"
base = "light"
backgroundColor = "#F4F6F9"
secondaryBackgroundColor = "#E8EFF7"
textColor = "#20354B"
font = "sans serif"
