[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#20745D"
base = "light"
backgroundColor = "#F8FAF9"
secondaryBackgroundColor = "#EEF3F1"
textColor = "#182B36"
font = "sans serif"
